'use strict'

/** @type {import('@adonisjs/lucid/src/Schema')} */
const Schema = use('Schema')

class RcuGasSchema extends Schema {
  up () {
    this.create('rcu_gas', (table) => {
      table.string('COD_PDR').primary()
      table.string('COD_REMI')
      table.string('CAPACITA_TRASPORTO')
      table.string('PRELIEVO_CONVENZIONALE_MAX')
      table.string('TIPO_PDR')
      table.string('DISALIMENTABILITA')
      table.string('PIVA_UDB')
      table.string('DATA_ABB_UDB')
      table.string('DEFAULT_TRAS')
      table.string('STATO_PDR')
      table.string('TIPO_SOSP')
      table.string('DATA_INIZIO_SOSP')
      table.string('DATA_FINE_SOSP')
      table.string('DATA_INIZIO_FOR')
      table.string('DATA_FINE_FOR')
      table.string('DATA_INIZIO_MAND')
      table.string('DATA_FINE_MAND')
      table.string('PIVA_CC').index()
      table.string('RAGIONE_SOCIALE_CC')
      table.string('PIVA_DD')
      table.string('RAGIONE_SOCIALE_DD')
      table.string('CF')
      table.string('PIVA')
      table.string('CF_STRANIERO')
      table.string('NOME')
      table.string('COGNOME')
      table.string('RAGIONE_SOCIALE_DENOMINAZIONE')
      table.string('EMAIL')
      table.string('TELEFONO')
      table.string('REFERENTE')
      table.string('REF_NOME')
      table.string('REF_COGNOME')
      table.string('REF_EMAIL')
      table.string('REF_TELEFONO')
      table.string('RESIDENZA')
      table.string('DATA_VAL_RES')
      table.string('AF_CF')
      table.string('AF_PIVA')
      table.string('AF_CF_STRANIERO')
      table.string('AF_NOME')
      table.string('AF_COGNOME')
      table.string('AF_RAGIONE_SOCIALE_DENOMINAZIONE')
      table.string('ALIQUOTA_IVA')
      table.string('ALIQUOTA_ACCISE')
      table.string('ADDIZ_REGIONALE')
      table.string('ALTRE_INFORMAZIONI')
      table.string('ACCESSO_UI')
      table.string('TIPO_FORNITURA')
      table.string('CODICE_UFFICIO')
      table.string('PAGAMENTO_IVA')
      table.string('SETT_MERCEOLOGICO')
      table.string('TRATTAMENTO')
      table.string('PREL_ANNUO_PREV')
      table.string('COD_PROF_PREL_STD')
      table.string('CAT_USO')
      table.string('CLASSE_PRELIEVO')
      table.string('ANNO_TERMICO')
      table.string('MATR_MIS')
      table.string('CLASSE_GRUPPO_MIS')
      table.string('TIPO_MIS')
      table.string('TELEGESTIONE')
      table.string('PRE_CONV')
      table.string('MATR_CONV')
      table.string('N_CIFRE_CONV')
      table.string('ANNO_FABB_CONV')
      table.string('DATA_INST_CONV')
      table.string('COEFF_CORR')
      table.string('PRESS_MISURA')
      table.string('ACC_MIS')
      table.string('N_CIFRE_MIS')
      table.string('ANNO_FABB_MIS')
      table.string('DATA_INST_MIS')
      table.string('GRUPPO_MIS_INT')
      table.string('POT_MAX_RIC')
      table.string('POT_TOT_INST')
      table.string('MAX_PRELIEVO_ORA')
      table.string('BONUS')
      table.string('BS_DATA_INIZIO')
      table.string('BS_DATA_FINE')
      table.string('BS_DATA_RINNOVO')
      table.string('TIPO_BONUS')
      table.string('EROG_SERVIZIO_ENERG')
      table.string('SE_PIVA')
      table.string('SE_RAGIONE_SOCIALE_DENOMINAZIONE')
      table.string('SE_TELEFONO')
      table.string('SE_EMAIL')      

      
    })
  }

  down () {
    this.drop('rcu_gas')
  }
}

module.exports = RcuGasSchema
